apiVersion: v1
kind: Secret
metadata:
  name: time-tracking-app-secrets
  namespace: fsavevsk-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql:/postgres-postgresql.fsavevsk-dev.svc.cluster.local:5432/timetracking"
  SPRING_DATASOURCE_USERNAME: "appuser"
  SPRING_DATASOURCE_PASSWORD: "topsecret"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://keycloak-tt-dev.3dss-non-prod.cloud.netcetera.com/realms/timetracking"