apiVersion: v1
kind: Secret
metadata:
  name: time-tracking-app-secrets
  namespace: fsavevsk-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "appuser"
  SPRING_DATASOURCE_PASSWORD: "topsecret"