spring:
  application:
    name: time-tracking-app
  datasource:
    url: jdbc:postgresql://localhost:5432/timetracker
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
