services:
  postgres:
    image: bitnami/postgresql:17.5.0
    environment:
      POSTGRES_USER: time-tracking-admin
      POSTGRES_PASSWORD: topsecret
      POSTGRES_DB: timetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:26.3.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DATABASE_VENDOR: dev-file
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
      - ./config:/opt/bitnami/keycloak/data/import

volumes:
  postgres_data:
    driver: local