global:
  storageClass: ebs-gp3

auth:
  username: appuser
  database: timetracking
  existingSecret: pg-auth  # Secret defined in extras/secret-dev.yaml

primary:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests: { cpu: "100m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }

  initdb:
    scripts:
      enable-extensions.sql: |
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        CREATE EXTENSION IF NOT EXISTS "pgcrypto";

readReplicas:
  replicaCount: 0

metrics:
  enabled: false

networkPolicy:
  enabled: false  # leave false if youâ€™ll apply your own policy in extras/networkpolicy.yaml
