ingress:
  enabled: true
  className: nginx
  hosts:
    - host: TBD
      paths:
        - path: /
          pathType: Prefix

egress:
  enabled: true
  matchName:
    - "TBD"
  ports:
    - 443

deployment:
  envFrom:
    - secretRef:
        name: time-tracking-app-secrets
  env:
    - name: SPRING_DATASOURCE_URL
      value: "TBD"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "TBD"