apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "time-tracking-app.fullname" . }}
  labels:
      {{- include "time-tracking-app.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ ternary "true" "false" .Values.image.debug | quote }}
  SPRING_DATASOURCE_USERNAME: {{ ternary "true" "false" .Values.production | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.logging.level | quote }}
  KC_LOG_CONSOLE_OUTPUT: {{ .Values.logging.output | quote }}
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.auth.adminUser | quote }}