apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "time-tracking-app.fullname" . }}
  labels:
    {{- include "time-tracking-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "time-tracking-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "time-tracking-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "time-tracking-app.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        node_group: 3dss-db
      tolerations:
        - key: "component"
          operator: "Equal"
          value: "3dss-db"
          effect: "NoSchedule"
      containers:
        - name: app
          {{- with .Values.deployment.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          {{- if .Values.deployment.envFrom }}
          envFrom:
          {{- toYaml .Values.deployment.envFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.env }}
          env:
          {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}