spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetracker
    username: time-tracking-admin
    password: topsecret
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dev
  flyway:
    enabled: true
    schemas: timetracker
    default-schema: timetracker
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true