spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetracker
    username: time-tracking-admin
    password: topsecret
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true